#!/usr/bin/env ruby

# Usage: textile2md [FILE]...
# Usage: cat FILE | textile2md
require 'textile2md'
require 'open-uri'

  if /\Ahttps?:/ =~ ARGV[0]
    filebody = OpenURI.open_uri(ARGV[0]).read
    puts Textile2md.convert(filebody)
  else
    puts Textile2md.convert(ARGF.read)
  end

